##########
REPLACE INTO `#__nbill_eu_tax_rate_info` (`country_code`, `tax_name`, `tax_abbreviation`, `tax_reference_desc`, `tax_rate`) VALUES
('AT', 'Umsatzsteuer', 'USt.', 'Ust.-Identifikationsnummer', 20.000000),
('BE', 'Belasting Toegevoegde Waarde', 'BTW', 'BTW-identificatienummer', 21.000000),
('BG', ' данък върху добавената стойност', 'ДДС', 'ДДС номер', 20.000000),
('CY', 'Φόρος Προστιθέμενης Αξίας', 'ΦΠΑ', 'Αριθμού Φορολογικού Μητρώου', 19.000000),
('CZ', 'Daň z přidané hodnoty', 'DPH', 'Daňové identifikační číslo', 21.000000),
('DE', 'Umsatzsteuer', 'USt.', 'Umsatzsteuer-Identifikationsnummer', 19.000000),
('DK', ' Merværdiafgift', 'MOMS', 'Momsnummer', 25.000000),
('EE', 'Käibemaksu', 'KM', 'käibemaksu registreerimisnumber', 20.000000),
('ES', 'Impuesto sobre el Valor Añadido', 'IVA', 'Número de IVA', 21.000000),
('FI', 'Arvonlisävero', 'ALV', 'Arvonlisäveronumero', 24.000000),
('FR', 'Taxe à la Valeur Ajoutée', 'TVA', 'Nombre de TVA', 20.000000),
('GB', 'Value Added Tax', 'VAT', 'VAT Number', 20.000000),
('GR', 'Φόρος Προστιθέμενης Αξίας', 'ΦΠΑ', 'Αριθμού Φορολογικού Μητρώου', 23.000000),
('HR', 'Porez na dodanu vrijednost', 'PDV', 'PDV Broj', 25.000000),
('HU', 'Áruforgalmi adó', 'ÁFA', 'ÁFA-szám', 27.000000),
('IE', 'Value Added Tax', 'VAT', 'VAT Number', 23.000000),
('IT', 'Imposta sul valore aggiunto', 'IVA', 'Numero di partita IVA', 22.000000),
('LT', 'Pridėtinės vertės mokestis', 'PVM', 'PVM mokėtojo kodas', 21.000000),
('LU', 'Taxe à la Valeur Ajoutée', 'TVA', 'Nombre de TVA', 15.000000),
('LV', 'Pievienotās vērtības nodoklis', 'PVN', 'PVN reģistrācijas numuru', 21.000000),
('MT', 'Valur Miżjud', 'VAT', 'Numru tal-VAT', 18.000000),
('NL', 'Belasting Toegevoegde Waarde', 'BTW', 'BTW-identificatienummer', 21.000000),
('PL', 'Podatek od towarów i usług', 'PTU', 'Numer VAT', 23.000000),
('PT', 'Imposto sobre o valor acrescentado', 'IVA', 'Número de IVA', 23.000000),
('RO', 'Taxa pe valoarea adăugată', 'TVA', 'Numărul de TVA', 24.000000),
('SE', 'Mervärdesskatt', 'MOMS', 'Momsnummer', 25.000000),
('SI', 'Davek na dodano vrednost', 'DDV', 'Identifikacijsko številko za DDV', 22.000000),
('SK', 'Daň z pridanej hodnoty', 'DPH', 'číslo DPH', 20.000000);
##########