##########
INSERT INTO `#__nbill_xref_states_au` (code, description) VALUES 
('ACT', 'Australian Capital Territory'), 
('NSW', 'New South Wales'), 
('NT', 'Northern Territory'), 
('QLD', 'Queensland'), 
('SA', 'South Australia'), 
('TAS', 'Tasmania'), 
('VIC', 'Victoria'), 
('WA', 'Western Australia'), 
('', 'OTHER');
##########
INSERT INTO `#__nbill_xref_states_ca` (code, description) VALUES 
('BC', 'British Columbia'), 
('AB', 'Alberta'), 
('MB', 'Manitoba'), 
('NB', 'New Brunswick'), 
('NL', 'Newfoundland and Labrador'), 
('NT', 'Northwest Territories'), 
('NS', 'Nova Scotia'), 
('NU', 'Nunavut'), 
('ON', 'Ontario'), 
('PE', 'Prince Edward Island'), 
('QC', 'Quebec'), 
('SK', 'Saskatchewan'), 
('YT', 'Yukon'), 
('', 'OTHER');
##########
INSERT INTO `#__nbill_xref_states_combined` (code, description) VALUES
('--United States--', '--United States--'),
('AL', 'Alabama'),
('AK', 'Alaska'),
('AS', 'American Samoa'),
('AZ', 'Arizona'),
('AR', 'Arkansas'),
('CA', 'California'),
('CO', 'Colorado'),
('CT', 'Connecticut'),
('DE', 'Delaware'),
('DC', 'District of Columbia'),
('FM', 'Federated States of Micronesia'),
('FL', 'Florida'),
('GA', 'Georgia'),
('GU', 'Guam'),
('HI', 'Hawaii'),
('ID', 'Idaho'),
('IL', 'Illinois'),
('IN', 'Indiana'),
('IA', 'Iowa'),
('KS', 'Kansas'),
('KY', 'Kentucky'),
('LA', 'Louisiana'),
('ME', 'Maine'),
('MH', 'Marshall Islands'),
('MD', 'Maryland'),
('MA', 'Massachusetts'),
('MI', 'Michigan'),
('MN', 'Minnesota'),
('MS', 'Mississippi'),
('MO', 'Missouri'),
('MT', 'Montana'),
('NE', 'Nebraska'),
('NV', 'Nevada'),
('NH', 'New Hampshire'),
('NJ', 'New Jersey'),
('NM', 'New Mexico'),
('NY', 'New York'),
('NC', 'North Carolina'),
('ND', 'North Dakota'),
('MP', 'Northern Mariana Islands'),
('OH', 'Ohio'),
('OK', 'Oklahoma'),
('OR', 'Oregon'),
('PW', 'Palau'),
('PA', 'Pennsylvania'),
('PR', 'Puerto Rico'),
('RI', 'Rhode Island'),
('SC', 'South Carolina'),
('SD', 'South Dakota'),
('TN', 'Tennessee'),
('TX', 'Texas'),
('UT', 'Utah'),
('VT', 'Vermont'),
('VI', 'Virgin Islands'),
('VA', 'Virginia'),
('WA', 'Washington'),
('WV', 'West Virginia'),
('WI', 'Wisconsin'),
('WY', 'Wyoming'),
('AA', 'Armed Forces Americas (except Canada)'),
('AP', 'Armed Forces Pacific'),
('AE', 'Armed Forces Other'),
('--Canada--', '--Canada--'),
('AB', 'Alberta'),
('BC', 'British Columbia'),
('MB', 'Manitoba'),
('NB', 'New Brunswick'),
('NL', 'Newfoundland and Labrador'),
('NT', 'Northwest Territories'),
('NS', 'Nova Scotia'),
('NU', 'Nunavut'),
('ON', 'Ontario'),
('PE', 'Prince Edward Island'),
('QC', 'Quebec'),
('SK', 'Saskatchewan'),
('YT', 'Yukon'),
('--United Kingdom--', '--United Kingdom--'),
('Avon', 'Avon'),
('Bedfordshire', 'Bedfordshire'),
('Buckinghamshire', 'Buckinghamshire'),
('Berkshire', 'Berkshire'),
('Cambridgeshire', 'Cambridgeshire'),
('Cheshire', 'Cheshire'),
('Cleveland', 'Cleveland'),
('Cumbria', 'Cumbria'),
('Cornwall', 'Cornwall'),
('Cumberland', 'Cumberland'),
('Derbyshire', 'Derbyshire'),
('Devon', 'Devon'),
('Dorset', 'Dorset'),
('Co. Durham', 'Co. Durham'),
('East Riding of Yorkshire', 'East Riding of Yorkshire'),
('Essex', 'Essex'),
('Gloucestershire', 'Gloucestershire'),
('Greater Manchester', 'Greater Manchester'),
('Hampshire', 'Hampshire'),
('Herefordshire', 'Herefordshire'),
('Hertfordshire', 'Hertfordshire'),
('Humberside', 'Humberside'),
('Huntingdonshire', 'Huntingdonshire'),
('Hereford and Worcester', 'Hereford and Worcester'),
('Isle of Wight', 'Isle of Wight'),
('Kent', 'Kent'),
('Lancashire', 'Lancashire'),
('Leicestershire', 'Leicestershire'),
('Lincolnshire', 'Lincolnshire'),
('London', 'London'),
('Middlesex', 'Middlesex'),
('Merseyside', 'Merseyside'),
('Northumberland', 'Northumberland'),
('Norfolk', 'Norfolk'),
('North Riding of Yorkshire', 'North Riding of Yorkshire'),
('Northamptonshire', 'Northamptonshire'),
('Nottinghamshire', 'Nottinghamshire'),
('North Yorkshire', 'North Yorkshire'),
('Oxfordshire', 'Oxfordshire'),
('Rutland', 'Rutland'),
('Shropshire', 'Shropshire'),
('Suffolk', 'Suffolk'),
('Somerset', 'Somerset'),
('Surrey', 'Surrey'),
('Sussex', 'Sussex'),
('Staffordshire', 'Staffordshire'),
('East Sussex', 'East Sussex'),
('West Sussex', 'West Sussex'),
('South Yorkshire', 'South Yorkshire'),
('Tyne and Wear', 'Tyne and Wear'),
('Warwickshire', 'Warwickshire'),
('Westmorland', 'Westmorland'),
('Wiltshire', 'Wiltshire'),
('West Midlands', 'West Midlands'),
('Worcestershire', 'Worcestershire'),
('West Riding of Yorkshire', 'West Riding of Yorkshire'),
('West Yorkshire', 'West Yorkshire'),
('Yorkshire', 'Yorkshire'),
('Anglesey', 'Anglesey'),
('Breconshire', 'Breconshire'),
('Caernarvonshire', 'Caernarvonshire'),
('Cardiganshire', 'Cardiganshire'),
('Carmarthenshire', 'Carmarthenshire'),
('Clwyd', 'Clwyd'),
('Denbighshire', 'Denbighshire'),
('Dyfed', 'Dyfed'),
('Flintshire', 'Flintshire'),
('Glamorgan', 'Glamorgan'),
('Gwent', 'Gwent'),
('Gwynedd', 'Gwynedd'),
('Merionethshire', 'Merionethshire'),
('Mid Glamorgan', 'Mid Glamorgan'),
('Montgomeryshire', 'Montgomeryshire'),
('Monmouthshire', 'Monmouthshire'),
('Pembrokeshire', 'Pembrokeshire'),
('Powys', 'Powys'),
('Radnorshire', 'Radnorshire'),
('South Glamorgan', 'South Glamorgan'),
('West Glamorgan', 'West Glamorgan'),
('Aberdeenshire', 'Aberdeenshire'),
('Angus', 'Angus'),
('Argyllshire', 'Argyllshire'),
('Ayrshire', 'Ayrshire'),
('Banffshire', 'Banffshire'),
('Berwickshire', 'Berwickshire'),
('Borders', 'Borders'),
('Bute', 'Bute'),
('Caithness', 'Caithness'),
('Central', 'Central'),
('Clackmannanshire', 'Clackmannanshire'),
('Dumfries-shire', 'Dumfries-shire'),
('Dumfries and Galloway', 'Dumfries and Galloway'),
('Dunbartonshire', 'Dunbartonshire'),
('East Lothian', 'East Lothian'),
('Fife', 'Fife'),
('Grampian', 'Grampian'),
('Highland', 'Highland'),
('Inverness-shire', 'Inverness-shire'),
('Kincardineshire', 'Kincardineshire'),
('Kirkcudbrightshire', 'Kirkcudbrightshire'),
('Kinross-shire', 'Kinross-shire'),
('Lanarkshire', 'Lanarkshire'),
('Lothian', 'Lothian'),
('Midlothian', 'Midlothian'),
('Morayshire', 'Morayshire'),
('Nairn', 'Nairn'),
('Orkney', 'Orkney'),
('Peebles-shire', 'Peebles-shire'),
('Perth', 'Perth'),
('Renfrewshire', 'Renfrewshire'),
('Ross and Cromarty', 'Ross and Cromarty'),
('Roxburghshire', 'Roxburghshire'),
('Selkirkshire', 'Selkirkshire'),
('Shetland', 'Shetland'),
('Strathclyde', 'Strathclyde'),
('Stirlingshire', 'Stirlingshire'),
('Sutherland', 'Sutherland'),
('Tayside', 'Tayside'),
('Wigtownshire', 'Wigtownshire'),
('Western Isles', 'Western Isles'),
('West Lothian', 'West Lothian'),
('Co. Antrim', 'Co. Antrim'),
('Co. Armagh', 'Co. Armagh'),
('Co. Down', 'Co. Down'),
('Co. Fermanagh', 'Co. Fermanagh'),
('Co. Londonderry', 'Co. Londonderry'),
('Co. Tyrone', 'Co. Tyrone'),
('Alderney', 'Alderney'),
('Guernsey', 'Guernsey'),
('Jersey', 'Jersey'),
('Sark', 'Sark'),
('--Ireland--', '--Ireland--'),
('Co. Carlow', 'Co. Carlow'),
('Co. Cavan', 'Co. Cavan'),
('Co. Clare', 'Co. Clare'),
('Co. Cork', 'Co. Cork'),
('Co. Donegal', 'Co. Donegal'),
('Co. Dublin', 'Co. Dublin'),
('Co. Galway', 'Co. Galway'),
('Co. Kerry', 'Co. Kerry'),
('Co. Kildare', 'Co. Kildare'),
('Co. Kilkenny', 'Co. Kilkenny'),
('Co. Leitrim', 'Co. Leitrim'),
('Co. Laois', 'Co. Laois'),
('Co. Limerick', 'Co. Limerick'),
('Co. Longford', 'Co. Longford'),
('Co. Louth', 'Co. Louth'),
('Co. Mayo', 'Co. Mayo'),
('Co. Meath', 'Co. Meath'),
('Co. Monaghan', 'Co. Monaghan'),
('Co. Offaly', 'Co. Offaly'),
('Co. Roscommon', 'Co. Roscommon'),
('Co. Sligo', 'Co. Sligo'),
('Co. Tipperary', 'Co. Tipperary'),
('Co. Waterford', 'Co. Waterford'),
('Co. Westmeath', 'Co. Westmeath'),
('Co. Wexford', 'Co. Wexford'),
('Co. Wicklow', 'Co. Wicklow'),
('--Australia--', '--Australia--'),
('ACT', 'Australian Capital Territory'), 
('NSW', 'New South Wales'), 
('NT', 'Northern Territory'), 
('QLD', 'Queensland'), 
('SA', 'South Australia'), 
('TAS', 'Tasmania'), 
('VIC', 'Victoria'), 
('WA', 'Western Australia'), 
('', 'OTHER');
##########
INSERT INTO `#__nbill_xref_states_ie` (code, description) VALUES
('Co. Carlow', 'Co. Carlow'),
('Co. Cavan', 'Co. Cavan'),
('Co. Clare', 'Co. Clare'),
('Co. Cork', 'Co. Cork'),
('Co. Donegal', 'Co. Donegal'),
('Co. Dublin', 'Co. Dublin'),
('Co. Galway', 'Co. Galway'),
('Co. Kerry', 'Co. Kerry'),
('Co. Kildare', 'Co. Kildare'),
('Co. Kilkenny', 'Co. Kilkenny'),
('Co. Leitrim', 'Co. Leitrim'),
('Co. Laois', 'Co. Laois'),
('Co. Limerick', 'Co. Limerick'),
('Co. Longford', 'Co. Longford'),
('Co. Louth', 'Co. Louth'),
('Co. Mayo', 'Co. Mayo'),
('Co. Meath', 'Co. Meath'),
('Co. Monaghan', 'Co. Monaghan'),
('Co. Offaly', 'Co. Offaly'),
('Co. Roscommon', 'Co. Roscommon'),
('Co. Sligo', 'Co. Sligo'),
('Co. Tipperary', 'Co. Tipperary'),
('Co. Waterford', 'Co. Waterford'),
('Co. Westmeath', 'Co. Westmeath'),
('Co. Wexford', 'Co. Wexford'),
('Co. Wicklow', 'Co. Wicklow'),
('', 'OTHER');
##########
INSERT INTO `#__nbill_xref_states_gb` (code, description) VALUES
('Avon', 'Avon'),
('Bedfordshire', 'Bedfordshire'),
('Buckinghamshire', 'Buckinghamshire'),
('Berkshire', 'Berkshire'),
('Cambridgeshire', 'Cambridgeshire'),
('Cheshire', 'Cheshire'),
('Cleveland', 'Cleveland'),
('Cumbria', 'Cumbria'),
('Cornwall', 'Cornwall'),
('Cumberland', 'Cumberland'),
('Derbyshire', 'Derbyshire'),
('Devon', 'Devon'),
('Dorset', 'Dorset'),
('Co. Durham', 'Co. Durham'),
('East Riding of Yorkshire', 'East Riding of Yorkshire'),
('Essex', 'Essex'),
('Gloucestershire', 'Gloucestershire'),
('Greater Manchester', 'Greater Manchester'),
('Hampshire', 'Hampshire'),
('Herefordshire', 'Herefordshire'),
('Hertfordshire', 'Hertfordshire'),
('Humberside', 'Humberside'),
('Huntingdonshire', 'Huntingdonshire'),
('Hereford and Worcester', 'Hereford and Worcester'),
('Isle of Wight', 'Isle of Wight'),
('Kent', 'Kent'),
('Lancashire', 'Lancashire'),
('Leicestershire', 'Leicestershire'),
('Lincolnshire', 'Lincolnshire'),
('London', 'London'),
('Middlesex', 'Middlesex'),
('Merseyside', 'Merseyside'),
('Northumberland', 'Northumberland'),
('Norfolk', 'Norfolk'),
('North Riding of Yorkshire', 'North Riding of Yorkshire'),
('Northamptonshire', 'Northamptonshire'),
('Nottinghamshire', 'Nottinghamshire'),
('North Yorkshire', 'North Yorkshire'),
('Oxfordshire', 'Oxfordshire'),
('Rutland', 'Rutland'),
('Shropshire', 'Shropshire'),
('Suffolk', 'Suffolk'),
('Somerset', 'Somerset'),
('Surrey', 'Surrey'),
('Sussex', 'Sussex'),
('Staffordshire', 'Staffordshire'),
('East Sussex', 'East Sussex'),
('West Sussex', 'West Sussex'),
('South Yorkshire', 'South Yorkshire'),
('Tyne and Wear', 'Tyne and Wear'),
('Warwickshire', 'Warwickshire'),
('Westmorland', 'Westmorland'),
('Wiltshire', 'Wiltshire'),
('West Midlands', 'West Midlands'),
('Worcestershire', 'Worcestershire'),
('West Riding of Yorkshire', 'West Riding of Yorkshire'),
('West Yorkshire', 'West Yorkshire'),
('Yorkshire', 'Yorkshire'),
('Anglesey', 'Anglesey'),
('Breconshire', 'Breconshire'),
('Caernarvonshire', 'Caernarvonshire'),
('Cardiganshire', 'Cardiganshire'),
('Carmarthenshire', 'Carmarthenshire'),
('Clwyd', 'Clwyd'),
('Denbighshire', 'Denbighshire'),
('Dyfed', 'Dyfed'),
('Flintshire', 'Flintshire'),
('Glamorgan', 'Glamorgan'),
('Gwent', 'Gwent'),
('Gwynedd', 'Gwynedd'),
('Merionethshire', 'Merionethshire'),
('Mid Glamorgan', 'Mid Glamorgan'),
('Montgomeryshire', 'Montgomeryshire'),
('Monmouthshire', 'Monmouthshire'),
('Pembrokeshire', 'Pembrokeshire'),
('Powys', 'Powys'),
('Radnorshire', 'Radnorshire'),
('South Glamorgan', 'South Glamorgan'),
('West Glamorgan', 'West Glamorgan'),
('Aberdeenshire', 'Aberdeenshire'),
('Angus', 'Angus'),
('Argyllshire', 'Argyllshire'),
('Ayrshire', 'Ayrshire'),
('Banffshire', 'Banffshire'),
('Berwickshire', 'Berwickshire'),
('Borders', 'Borders'),
('Bute', 'Bute'),
('Caithness', 'Caithness'),
('Central', 'Central'),
('Clackmannanshire', 'Clackmannanshire'),
('Dumfries-shire', 'Dumfries-shire'),
('Dumfries and Galloway', 'Dumfries and Galloway'),
('Dunbartonshire', 'Dunbartonshire'),
('East Lothian', 'East Lothian'),
('Fife', 'Fife'),
('Grampian', 'Grampian'),
('Highland', 'Highland'),
('Inverness-shire', 'Inverness-shire'),
('Kincardineshire', 'Kincardineshire'),
('Kirkcudbrightshire', 'Kirkcudbrightshire'),
('Kinross-shire', 'Kinross-shire'),
('Lanarkshire', 'Lanarkshire'),
('Lothian', 'Lothian'),
('Midlothian', 'Midlothian'),
('Morayshire', 'Morayshire'),
('Nairn', 'Nairn'),
('Orkney', 'Orkney'),
('Peebles-shire', 'Peebles-shire'),
('Perth', 'Perth'),
('Renfrewshire', 'Renfrewshire'),
('Ross and Cromarty', 'Ross and Cromarty'),
('Roxburghshire', 'Roxburghshire'),
('Selkirkshire', 'Selkirkshire'),
('Shetland', 'Shetland'),
('Strathclyde', 'Strathclyde'),
('Stirlingshire', 'Stirlingshire'),
('Sutherland', 'Sutherland'),
('Tayside', 'Tayside'),
('Wigtownshire', 'Wigtownshire'),
('Western Isles', 'Western Isles'),
('West Lothian', 'West Lothian'),
('Co. Antrim', 'Co. Antrim'),
('Co. Armagh', 'Co. Armagh'),
('Co. Down', 'Co. Down'),
('Co. Fermanagh', 'Co. Fermanagh'),
('Co. Londonderry', 'Co. Londonderry'),
('Co. Tyrone', 'Co. Tyrone'),
('Alderney', 'Alderney'),
('Guernsey', 'Guernsey'),
('Jersey', 'Jersey'),
('Sark', 'Sark'),
('', 'OTHER');
##########
INSERT INTO `#__nbill_xref_states_us` (code, description) VALUES
('AL', 'Alabama'),
('AK', 'Alaska'),
('AS', 'American Samoa'),
('AZ', 'Arizona'),
('AR', 'Arkansas'),
('CA', 'California'),
('CO', 'Colorado'),
('CT', 'Connecticut'),
('DE', 'Delaware'),
('DC', 'District of Columbia'),
('FM', 'Federated States of Micronesia'),
('FL', 'Florida'),
('GA', 'Georgia'),
('GU', 'Guam'),
('HI', 'Hawaii'),
('ID', 'Idaho'),
('IL', 'Illinois'),
('IN', 'Indiana'),
('IA', 'Iowa'),
('KS', 'Kansas'),
('KY', 'Kentucky'),
('LA', 'Louisiana'),
('ME', 'Maine'),
('MH', 'Marshall Islands'),
('MD', 'Maryland'),
('MA', 'Massachusetts'),
('MI', 'Michigan'),
('MN', 'Minnesota'),
('MS', 'Mississippi'),
('MO', 'Missouri'),
('MT', 'Montana'),
('NE', 'Nebraska'),
('NV', 'Nevada'),
('NH', 'New Hampshire'),
('NJ', 'New Jersey'),
('NM', 'New Mexico'),
('NY', 'New York'),
('NC', 'North Carolina'),
('ND', 'North Dakota'),
('MP', 'Northern Mariana Islands'),
('OH', 'Ohio'),
('OK', 'Oklahoma'),
('OR', 'Oregon'),
('PW', 'Palau'),
('PA', 'Pennsylvania'),
('PR', 'Puerto Rico'),
('RI', 'Rhode Island'),
('SC', 'South Carolina'),
('SD', 'South Dakota'),
('TN', 'Tennessee'),
('TX', 'Texas'),
('UT', 'Utah'),
('VT', 'Vermont'),
('VI', 'Virgin Islands'),
('VA', 'Virginia'),
('WA', 'Washington'),
('WV', 'West Virginia'),
('WI', 'Wisconsin'),
('WY', 'Wyoming'),
('AA', 'Armed Forces Americas (except Canada)'),
('AP', 'Armed Forces Pacific'),
('AE', 'Armed Forces Other'),
('', 'OTHER');
##########
INSERT INTO `#__nbill_xref_states_us_and_ca` (code, description) VALUES
('--United States--', '--United States--'),
('AL', 'Alabama'),
('AK', 'Alaska'),
('AS', 'American Samoa'),
('AZ', 'Arizona'),
('AR', 'Arkansas'),
('CA', 'California'),
('CO', 'Colorado'),
('CT', 'Connecticut'),
('DE', 'Delaware'),
('DC', 'District of Columbia'),
('FM', 'Federated States of Micronesia'),
('FL', 'Florida'),
('GA', 'Georgia'),
('GU', 'Guam'),
('HI', 'Hawaii'),
('ID', 'Idaho'),
('IL', 'Illinois'),
('IN', 'Indiana'),
('IA', 'Iowa'),
('KS', 'Kansas'),
('KY', 'Kentucky'),
('LA', 'Louisiana'),
('ME', 'Maine'),
('MH', 'Marshall Islands'),
('MD', 'Maryland'),
('MA', 'Massachusetts'),
('MI', 'Michigan'),
('MN', 'Minnesota'),
('MS', 'Mississippi'),
('MO', 'Missouri'),
('MT', 'Montana'),
('NE', 'Nebraska'),
('NV', 'Nevada'),
('NH', 'New Hampshire'),
('NJ', 'New Jersey'),
('NM', 'New Mexico'),
('NY', 'New York'),
('NC', 'North Carolina'),
('ND', 'North Dakota'),
('MP', 'Northern Mariana Islands'),
('OH', 'Ohio'),
('OK', 'Oklahoma'),
('OR', 'Oregon'),
('PW', 'Palau'),
('PA', 'Pennsylvania'),
('PR', 'Puerto Rico'),
('RI', 'Rhode Island'),
('SC', 'South Carolina'),
('SD', 'South Dakota'),
('TN', 'Tennessee'),
('TX', 'Texas'),
('UT', 'Utah'),
('VT', 'Vermont'),
('VI', 'Virgin Islands'),
('VA', 'Virginia'),
('WA', 'Washington'),
('WV', 'West Virginia'),
('WI', 'Wisconsin'),
('WY', 'Wyoming'),
('AA', 'Armed Forces Americas (except Canada)'),
('AP', 'Armed Forces Pacific'),
('AE', 'Armed Forces Other'),
('--Canada--', '--Canada--'),
('AB', 'Alberta'),
('BC', 'British Columbia'),
('MB', 'Manitoba'),
('NB', 'New Brunswick'),
('NL', 'Newfoundland and Labrador'),
('NT', 'Northwest Territories'),
('NS', 'Nova Scotia'),
('NU', 'Nunavut'),
('ON', 'Ontario'),
('PE', 'Prince Edward Island'),
('QC', 'Quebec'),
('SK', 'Saskatchewan'),
('YT', 'Yukon'),
('', 'OTHER');
##########