<?php
/**
* Language file for the Payment Gateway list
* @version 2
* @package nBill
* @copyright (C) 2015 Netshine Software Limited
* @license GPL v2 (LITE edition only. Standard Edition is NOT licensed under the GPL)
*
* @access private*
*/

//Ensure this file has been reached through a valid entry point (not always necessary eg. for class files, but included on every file to be safe!)
(defined('_VALID_MOS') || defined('_JEXEC') || defined('ABSPATH') || defined('NBILL_VALID_NBF')) or die('Access Denied.');

//Payment Gateway
define("NBILL_AUTO_GENERATED_INCOME", "Auto Generated by Payment Gateway.");
define("NBILL_GATEWAY_ERROR", NBILL_BRANDING_NAME . " Error Report");
define("NBILL_ERR_RECEIPT_NOT_PROCESSED", "A receipt notification for %s was received, but could not be processed because it could not be matched with an existing order or invoice. If you use " . NBILL_BRANDING_NAME . " to reconcile all of your transactions, you may need to add the income item manually.");
define("NBILL_GATEWAY_TITLE", "Payment Gateways");
define("NBILL_GATEWAY_INTRO", "Payment gateways are to allow you to use an online payment service provider to accept credit card payments. In order to add online payment features to your order forms, you will need a payment gateway extension specifically built for " . NBILL_BRANDING_NAME . " and your payment service provider. For details of payment gateway extensions that are currently available, please refer to the " . NBILL_BRANDING_NAME . " Website (%s).");
define("NBILL_GATEWAY_NAME", "Gateway Name");
define("NBILL_GATEWAY_DESCRIPTION", "Description");
define("NBILL_EDIT_GATEWAY", "Edit Gateway Settings");
define("NBILL_ERR_GATEWAY_PROBLEM", "There is a problem with this payment gateway. The action you requested could not be performed.");
define("NBILL_GATEWAY_SETTINGS", "Payment Gateway Settings");
define("NBILL_CONFIRM_UNINSTALL_GATEWAY", "WARNING! This will completely uninstall this payment gateway!");
define("NBILL_ERR_GATEWAY_NOT_REMOVED", "WARNING! Although the payment gateway has been deleted from " . NBILL_BRANDING_NAME . ", not all of the related files could be deleted.");
define("NBILL_ERR_GATEWAY_NOT_FOUND", "ERROR: The payment gateway associated with this order form or invoice could not be found. It will not be possible to pay online at the present time.");
define("NBILL_GATEWAY_WARNING", NBILL_BRANDING_NAME . " Warning Report");
define("NBILL_GATEWAY_ERR_ORDER_NOT_FOUND", "Gateway transaction '%s' not found");
define("NBILL_GATEWAY_INSTALL_WARNING", "WARNING! Only install payment gateways from trusted sources. A gateway script can access your entire website!");
define("NBILL_GATEWAY_CALLBACK_INFO", "The following information shows the contents of the \$_REQUEST and \$_SERVER PHP variables. A technician may find this information useful in determining why the error occurred.\n\n");
define("NBILL_GATEWAY_FILES_MISSING", "WARNING! The database tables for gateway '%s' are present in the database, but the gateway files are missing. This may be because you have upgraded " . NBILL_BRANDING_NAME . ". Please either re-install this payment gateway by clicking on the 'New' toolbar button above (your settings will be preserved), or delete it (which will permanently destroy all traces of this gateway).");
define("NBILL_GATEWAY_ERR", "A problem occurred whilst attempting to process your payment. The following error was returned: %s<br /><br />Please contact us if you need assistance.");
define("NBILL_GATEWAY_SUCCESS", "Thank you - your payment was received successfully."); //Note: You can use the following placeholders to represent transaction data which can be output in the thank you message (for use when integrating with affiliate tracking programs or to provide a custom payment confirmation screen): ##TX_ID## (transaction ID); ##AMOUNT## (amount of payment); ##CURRENCY## (currency used); ##ORDER_ID## (order record ID number, if known); ##ORDER_NO## (order number, if known). A transaction ID will always exist, but an order record might not.
define("NBILL_GATEWAY_ERR_AMOUNT_MISMATCH", "ERROR - Amount mismatch (the amount received was different to the amount expected). Amount expected: %s; Amount received: %s");
define("NBILL_GATEWAY_ERR_DUPLICATE_NOTIFICATION", "ERROR - Duplicate notification of payment.");/**************/
/* Version 1.1.4
/* Note to translators: Text amended for NBILL_GATEWAY_ERR (line 42 in the en-GB file).
/**************/

//Version 1.2.0
define("NBILL_GATEWAY_DISPLAY_NAME", "Display Name");
define("NBILL_GATEWAY_PUBLISHED", "Published?");
//define("NBILL_INSTR_GATEWAY_DISPLAY_NAME", "Used in a dropdown list for allowing user to select a gateway when renewing an order or paying an invoice. Note: When user selects a gateway on an order form, you must specify the display name to use in the field options. This setting is only for occasions when payments are made without using an order form.");
//define("NBILL_INSTR_GATEWAY_PUBLISHED", "Whether or not this gateway should appear in a dropdown list for allowing a user to select a gateway. Note: This only applies to selection of a gateway when not using an order form. On an order form, you have to manually define which gateways are allowed, so this setting makes no difference there (ie. you can still use a gateway on an order form even if it is not published, but it cannot be used for paying an invoice or renewing an order unless it is published).");

//Version 2.0.1
define("NBILL_GATEWAY_NO_RECURRING", "Sorry, this payment gateway does not support recurring payments");
define("NBILL_GATEWAY_DOES_NOT_SUPPORT_FREQUENCY", "Sorry, this payment gateway does not support the selected payment frequency");
define("NBILL_GATEWAY_NO_FREE_TRIALS", "Sorry, this payment gateway does not support free trials");
define("NBILL_GATEWAY_NO_FIRST_PAYMENT_DIFFERENT", "Sorry, this payment gateway does not support having a different amount for the first payment than for the recurring payments");
define("NBILL_GATEWAY_NO_FIXED_INSTALLMENTS", "Sorry, this payment gateway does not support a fixed number of payments");
define("NBILL_GATEWAY_MIN_PAYMENTS", "Sorry, this payment gateway only allows a minimum of %s payments");
define("NBILL_GATEWAY_ERR_SUFFIX", " - it will not be possible to pay for this order online.");

//Version 2.1.0
define("NBILL_GATEWAY_FEE_OR_DISCOUNT_CODE", "Fee or Discount Code");
define("NBILL_INSTR_GATEWAY_FEE_OR_DISCOUNT_CODE", "You can specify a voucher code here which can be used to apply either a fee or a discount (with a matching code) whenever someone pays using this payment method (by specifying a voucher code rather than the actual fee or discount, you can allow more than one fee or discount to be applied). All voucher codes that have been defined on your fee or discount records will be listed here. WARNING! Using this feature can cause invoice totals to be changed after the invoice has been created (to apply the gateway fee at the time of payment). If you want to use this feature then, make sure it is legal in your country to change an invoice amount even after the customer has received the invoice (if applicable). Please also note that while this feature has been tested fairly thoroughly, it should still be regarded as experimental. Due to rounding differences in the way amounts are calculated, and the way partial payments are dealt with, it might not always yield the desired or expected results.");
define("NBILL_GATEWAY_ORDERING", "Ordering");
define("NBILL_GATEWAY_OFFLINE_DESC", "Special built-in gateway for allowing selection of an offline payment method such as cash, cheque, or bank transfer.");

//Version 2.3.2
define("NBILL_WARNING_WO_INVOICE", "WARNING! A client has just paid an invoice which had been written off.");
define("NBILL_WARNING_WO_INVOICE_CANCELLED_ORDER", "The written off invoice was related to an order record which has been cancelled - it might be necessary to re-instate the order.");

//Version 2.5.2
define("NBILL_INSTR_GATEWAY_DISPLAY_NAME_2", "Used whenever the gateway name is displayed on your website (eg. when choosing a payment method while paying an invoice or renewing an order).");
define("NBILL_INSTR_GATEWAY_PUBLISHED_2", "Whether or not this gateway should appear in a dropdown list for allowing a user to select a gateway.");
define("NBILL_GATEWAY_SUCCESS_PENDING", "Thank you - your payment instruction was received successfully and is pending confirmation.");
define("NBILL_GATEWAY_EXTRA_FUNCTIONS", "NOTE: This gateway has additional features. %s to access the extra functions for this gateway.");

//Version 3.1.1
define("NBILL_GATEWAY_ERR_DUPLICATE_NOTIFICATION_TXN", "ERROR - Duplicate notification of payment (transaction reference: %s, gateway transaction ID: %s).");